CREATE TABLE antismash.as_domain_profiles (
    as_domain_profile_id	serial NOT NULL,
    name	text NOT NULL,
    description	text NOT NULL,
    database	text NOT NULL,
    type	    text,
    CONSTRAINT as_domain_profiles_pkey PRIMARY KEY (as_domain_profile_id)
);

COMMENT ON TABLE antismash.as_domain_profiles IS
  'A functional secondary metabolite domain profile predicted by antiSMASH';

INSERT INTO antismash.as_domain_profiles (name, description, database, type)
VALUES
    ('Beta_elim_lyase', 'Beta-eliminating lyase', 'nrpspksdomains.hmm', NULL),
    ('Condensation', 'Condensation domain', 'nrpspksdomains.hmm', 'condensation'),
    ('Condensation_DCL', 'Condensation domain that links L-amino acid to peptide ending with D-amino acid', 'nrpspksdomains.hmm', 'condensation'),
    ('Condensation_LCL', 'Condensation domain that links L-amino acid to peptide ending with L-amino acid', 'nrpspksdomains.hmm', 'condensation'),
    ('Condensation_Dual', 'Dual condensation/epimerization domain', 'nrpspksdomains.hmm', 'condensation'),
    ('Condensation_Starter', 'Starter condensation domain', 'nrpspksdomains.hmm', 'condensation'),
    ('X', 'Glycopeptide-specific NRPS domain responsible for oxygenase recruitment', 'nrpspksdomains.hmm', NULL),
    ('Cglyc', 'Glycopeptide condensation domain', 'nrpspksdomains.hmm', 'condensation'),
    ('Heterocyclization', 'Heterocyclization domain', 'nrpspksdomains.hmm', NULL),
    ('Epimerization', 'Epimerization domain', 'nrpspksdomains.hmm', NULL),
    ('ACPS', '4''-phosphopantetheinyl transferase', 'nrpspksdomains.hmm', NULL),
    ('MT', 'methyl transferase', 'nrpspksdomains.hmm', 'methyl transferase'),
    ('cMT', 'C-methyl transferase', 'nrpspksdomains.hmm', 'methyl transferase'),
    ('oMT', 'O-methyl transferase', 'nrpspksdomains.hmm', 'methyl transferase'),
    ('nMT', 'N-methyl transferase', 'nrpspksdomains.hmm', 'methyl transferase'),
    ('AMP-binding', 'Adenylation domain', 'nrpspksdomains.hmm', 'adenylation'),
    ('A-OX', 'Adenylation domain with integrated oxidase', 'nrpspksdomains.hmm', 'adenylation'),
    ('TauD', 'Taurine catabolism dioxygenase TauD, TfdA family', 'nrpspksdomains.hmm', NULL),
    ('Thioesterase', 'Thioesterase domain', 'nrpspksdomains.hmm', NULL),
    ('TD', 'Terminal reductase domain', 'nrpspksdomains.hmm', NULL),
    ('Aminotran_1_2', 'Aminotransferase class I + II', 'nrpspksdomains.hmm', 'aminotransferase'),
    ('Aminotran_3', 'Aminotransferase class III', 'nrpspksdomains.hmm', 'aminotransferase'),
    ('Aminotran_4', 'Aminotransferase class IV', 'nrpspksdomains.hmm', 'aminotransferase'),
    ('Aminotran_5', 'Aminotransferase class V', 'nrpspksdomains.hmm', 'aminotransferase'),
    ('PKS_KS', 'Ketosynthase domain', 'nrpspksdomains.hmm', NULL),
    ('PKS_KR', 'Ketoreductase domain', 'nrpspksdomains.hmm', NULL),
    ('PKS_ER', 'Enoylreductase domain', 'nrpspksdomains.hmm', NULL),
    ('PKS_DH', 'Dehydrogenase domain', 'nrpspksdomains.hmm', NULL),
    ('PKS_DH2', 'Dehydrogenase-2 domain', 'nrpspksdomains.hmm', NULL),
    ('PKS_DHt', 'Dehydrogenase domain more commonly found in Trans-AT clusters', 'nrpspksdomains.hmm', NULL),
    ('PKS_AT', 'Acyltransferase domain', 'nrpspksdomains.hmm', NULL),
    ('NRPS-COM_Nterm', 'NRPS COM domain N-terminal', 'nrpspksdomains.hmm', NULL),
    ('NRPS-COM_Cterm', 'NRPS COM domain C-terminal', 'nrpspksdomains.hmm', NULL),
    ('Polyketide_cyc', 'Polyketide cyclase', 'nrpspksdomains.hmm', NULL),
    ('Polyketide_cyc2', 'Polyketide cyclase/dehydratase', 'nrpspksdomains.hmm', NULL),
    ('PKS_Docking_Nterm', 'PKS N-terminal docking domain', 'nrpspksdomains.hmm', NULL),
    ('PKS_Docking_Cterm', 'PKS C-terminal docking domain', 'nrpspksdomains.hmm', NULL),
    ('CAL_domain', 'Co-enzyme A ligase domain', 'nrpspksdomains.hmm', NULL),
    ('SAT', 'Starter unit ACP transacylase domain', 'nrpspksdomains.hmm', NULL),
    ('Trans-AT_docking', 'Trans-acyltransferase docking domain', 'nrpspksdomains.hmm', NULL),
    ('ACP', 'Acyl-carrier protein domain', 'nrpspksdomains.hmm', 'transporter'),
    ('PCP', 'Peptidyl-carrier protein domain', 'nrpspksdomains.hmm', 'transporter'),
    ('PP-binding', 'Phosphopantetheine attachment site, thiolation domain', 'nrpspksdomains.hmm', 'transporter'),
    ('PKS_PP', 'Phosphopantetheine acyl carrier protein group', 'nrpspksdomains.hmm', 'transporter'),
    ('NAD_binding_4', 'Male sterility protein', 'nrpspksdomains.hmm', NULL),
    ('ACP_beta', 'beta-branching acyl-carrier protein domain', 'nrpspksdomains.hmm', 'transporter'),
    ('B', 'branching domain', 'nrpspksdomains.hmm', NULL),
    ('F', 'Formylation domain', 'nrpspksdomains.hmm', NULL),
    ('FkbH', 'FkbH-like domain', 'nrpspksdomains.hmm', NULL),
    ('GNAT', 'GNAT domain', 'nrpspksdomains.hmm', NULL),
    ('Hal', 'Halogenase domain', 'nrpspksdomains.hmm', NULL),
    ('PS', 'Pyran synthase domain', 'nrpspksdomains.hmm', NULL),
    ('PT', 'Fungal nonreducing product template domain', 'nrpspksdomains.hmm', NULL),
    ('TIGR01720', 'NRPS_para261: non-ribosomal peptide synthase domain', 'nrpspksdomains.hmm', NULL),
    ('ECH', 'Enoyl-CoA hydratase/isomerase', 'nrpspksdomains.hmm', NULL),
    ('TIGR02353', 'NRPS terminal domain of unknown function', 'nrpspksdomains.hmm', NULL);
