CREATE TABLE antismash.monomers (
    monomer_id	serial NOT NULL,
    name	text,
    description	text,
    smile	text,
    three_letter_code	char(3),
    single_letter_code	char(1),
    CONSTRAINT monomers_pkey PRIMARY KEY (monomer_id),
    CONSTRAINT monomers_name_unique UNIQUE (name)
);

COMMENT ON TABLE antismash.monomers IS
  'A basic building block of a compound.';

INSERT INTO antismash.monomers (name, description, three_letter_code, single_letter_code)
VALUES
    ('d-dbu', '(2R,3R)-2,3-diaminobutyric acid', NULL, NULL),
    ('dbu', '(2S)-2,3-diaminobutyric acid', NULL, NULL),
    ('l-dbu', '(2S,3S)-2,3-diaminobutyric acid', NULL, NULL),
    ('ome-bala-thz', '1-methoxy-beta-alanine-thiazole', NULL, NULL),
    ('dhabu', '2,3-dehydro-2-aminobutyric acid', NULL, NULL),
    ('dh-trp', '2,3-Dehydro-Tryptophan', NULL, NULL),
    ('dpr', '2,3-Diaminopropionic acid', NULL, NULL),
    ('dhb', '2,3-dihydroxybenzoic acid', NULL, NULL),
    ('2me-3me-pglu', '2,3-dimethylpyroglutamic acid', NULL, NULL),
    ('dab', '2,4-diaminobutyric acid', NULL, NULL),
    ('daz', '2,6-diamino-7-hydroxyazelaic acid', NULL, NULL),
    ('aeo', '2-amino-9,10-epoxi-8-oxodecanoic acid', NULL, NULL),
    ('aad', '2-Aminoadipic acid', NULL, NULL),
    ('abu', '2-Aminobutyric acid', NULL, NULL),
    ('aib', '2-Aminoisobutyric acid', NULL, NULL),
    ('br-oh-trp', '2-bromo-5-hydroxytryptophan', NULL, NULL),
    ('choi', '2-carboxy-6-hydroxyoctahydroindole', NULL, NULL),
    ('cooh-qui', '2-carboxyquinoxaline', NULL, NULL),
    ('hmp', '2-hydroxy-3-methyl-pentanoic acid', NULL, NULL),
    ('hiv', '2-hydroxyisovalerate', NULL, NULL),
    ('hpoe', '2-hydroxyphenyl-2-oxo-ethanoic acid', NULL, NULL),
    ('mab', '2-methyl-3-aminobutanoic acid', NULL, NULL),
    ('map', '2-methyl-3-aminopentanoic acid', NULL, NULL),
    ('2dh-mabu', '2-methylamino-2-dehydrobutyric acid', NULL, NULL),
    ('2metbut', '2-Methylbutyryl-CoA', NULL, NULL),
    ('cl2-pro', '3,4-dichloro-proline', NULL, NULL),
    ('dioh-arg', '3,4-dihydroxyArginine', NULL, NULL),
    ('34dhb', '3,4-dihydroxybenzoate', NULL, NULL),
    ('dioh-phe', '3,4-dihydroxyphenylalanine', NULL, NULL),
    ('3me-4me-gln', '3,4-dimethylglutamine', NULL, NULL),
    ('ahba', '3,5-AHBA-CoA', NULL, NULL),
    ('cl2-hpg', '3,5-dichloro-4-hydroxyphenylglycine', NULL, NULL),
    ('dhpg', '3,5-dihydroxyphenylglycine', NULL, NULL),
    ('ammetprop', '3-Amino-2-Methylpropionate', NULL, NULL),
    ('ahp', '3-amino-6-hydroxy-2-piperidone', NULL, NULL),
    ('cl-hpg', '3-chloro-4-hydroxyphenylglycine', NULL, NULL),
    ('3d-nme-bmt', '3-Desoxy-Methyl-4-butenyl-4-methyl threonine', NULL, NULL),
    ('3oh-5me-pro', '3-Hydroxy-5-methylproline', NULL, NULL),
    ('3oh-leu', '3-hydroxyleucine', NULL, NULL),
    ('3oh-pro', '3-Hydroxyproline', NULL, NULL),
    ('3metbut', '3-Methylbutyryl-CoA', NULL, NULL),
    ('3me-glu', '3-Methyl-Glutamic acid', NULL, NULL),
    ('3-me-glu', '3-methylglutamine', NULL, NULL),
    ('3me-hty', '3-methyl-homotyrosine', NULL, NULL),
    ('3me-phe', '3-methylphenylalanine', NULL, NULL),
    ('3me-pro', '3-methylproline', NULL, NULL),
    ('me-vaa', '3-methylvaleric acid', NULL, NULL),
    ('3no2-tyr', '3-nitrotyrosine', NULL, NULL),
    ('ibu', '4-amino-2,2-dimethyl-3-oxopentanoic acid', NULL, NULL),
    ('oh-4abu', '4-amino-3-hydroxybutyric acid', NULL, NULL),
    ('agdha', '4-amino-7-guanidino-2,3-dihydroxyheptanoic acid', NULL, NULL),
    ('bmt', '4-butenyl-4-methyl threonine', NULL, NULL),
    ('me2-bmt', '4-butenyl-4-methyl-N,4-methyl threonine', NULL, NULL),
    ('4cl-thr', '4-Chloro-Threonine', NULL, NULL),
    ('4oh-d-ph-lac', '4-hydroxy-D-phenyl-lactate', NULL, NULL),
    ('4oh-pro', '4-Hydroxyproline', NULL, NULL),
    ('4oh-thr', '4-Hydroxythreonine', NULL, NULL),
    ('4mha', '4-methyl-3-hydroxyanthranilic acid', NULL, NULL),
    ('4me-d-hva', '4-Methyl-D-2-hydroxy-valeric acid', NULL, NULL),
    ('4me-pro', '4-methylproline', NULL, NULL),
    ('4oxo-5me-pro', '4-oxo-5-methylproline', NULL, NULL),
    ('4oxo-hpr', '4-oxo-homoproline', NULL, NULL),
    ('4oxo-pro', '4-oxo-proline', NULL, NULL),
    ('4oxo-van', '4-oxovancosamine', NULL, NULL),
    ('ptta', '4-propenoyl-2-tyrosylthiazole acid', NULL, NULL),
    ('4ppro', '4-propyl-L-proline', NULL, NULL),
    ('chrd', '5,6-dihydropyoverdin chromophore', NULL, NULL),
    ('br-trp', '5-bromo-tryptophan', NULL, NULL),
    ('5oh-cap', '5-hydroxy-capreomycidine', NULL, NULL),
    ('oh-trp', '5-hydroxytryptophan', NULL, NULL),
    ('5me-pro', '5-methylproline', NULL, NULL),
    ('dhmda', '8,10-Dimethyl-9-hydroxy-7-methoxytridecadienoic acid', NULL, NULL),
    ('acace', 'Acetoacetyl-CoA', NULL, NULL),
    ('ace', 'Acetyl-CoA', NULL, NULL),
    ('chract', 'actinomycin chromophore', NULL, NULL),
    ('ala', 'Alanine', 'Ala', 'A'),
    ('ala-thz', 'Alanine-thiazole', NULL, NULL),
    ('aile', 'allo-Isoleucine', NULL, NULL),
    ('athr', 'allo-Threonine', NULL, NULL),
    ('ccmal', 'reduced malonyl (a derivative of malonyl-CoA reduced by ketoreductase and dehydrated by dehydratase)', NULL, NULL),
    ('ccmmal', 'reduced methylmalonyl (a derivative of methylmalonyl-CoA reduced by ketoreductase and dehydrated by dehydratase)', NULL, NULL),
    ('ccmxmal', 'reduced methoxymalonyl (a derivative of methoxymalonyl-CoA reduced by ketoreductase and dehydrated by dehydratase)', NULL, NULL),
    ('ahad', 'alpha-amino-hydroxyadipic acid', NULL, NULL),
    ('ahv', 'alpha-amino-hydroxyphenyl-valeric acid', NULL, NULL),
    ('amv', 'alpha-amino-methoxyphenyl-valeric acid', NULL, NULL),
    ('apv', 'alpha-amino-phenyl-valeric acid', NULL, NULL),
    ('et-nva', 'alpha-ethylnorvaline', NULL, NULL),
    ('afo-gly', 'alpha-formylGlycine', NULL, NULL),
    ('gser', 'alpha-guanidino Serine', NULL, NULL),
    ('k-arg', 'alpha-ketoarginine', NULL, NULL),
    ('ame-cys', 'alpha-methylcysteine', NULL, NULL),
    ('amal', 'Aminomalonyl-CoA', NULL, NULL),
    ('aca', 'Anticapsin', NULL, NULL),
    ('argal', 'arginal', NULL, NULL),
    ('arg', 'Arginine', 'Arg', 'R'),
    ('asn', 'Asparigine', 'Asn', 'N'),
    ('asp', 'Aspartate', 'Asp', 'D'),
    ('azd', 'aziridine dicarboxylic acid', NULL, NULL),
    ('chra', 'azotobactins chromophore', NULL, NULL),
    ('bz', 'benzoic acid', NULL, NULL),
    ('benz', 'Benzoyl-CoA', NULL, NULL),
    ('blys', 'beta lysine', NULL, NULL),
    ('bphe', 'beta phenylalanine', NULL, NULL),
    ('bbnme-nme-trp', 'beta,beta,N1,N-tetramethyltryptophan', NULL, NULL),
    ('bbme-nme-trp', 'beta,beta,N-trimethyltryptophan', NULL, NULL),
    ('bbme2-o-met', 'beta,beta-dimethyl-Methionine-S-oxide', NULL, NULL),
    ('b-ala', 'beta-Alanine', NULL, NULL),
    ('ohmal', 'hydroxymalonyl (a derivative of malonyl-CoA reduced by ketoreductase)', NULL, NULL),
    ('ohmmal', 'hydroxymethylmalonyl (a derivative of metylmalonyl-CoA reduced by ketoreductase)', NULL, NULL),
    ('ohmxmal', 'hydroxymethoxymalonyl (a derivative of methoxymalonyl-CoA reduced by ketoreductase)', NULL, NULL),
    ('boh-br-phe', 'beta-hydroxy-bromophenylalanine', NULL, NULL),
    ('boh-cl-tyr', 'beta-hydroxy-chloro-tyrosine', NULL, NULL),
    ('boh-gln', 'beta-hydroxyglutamine', NULL, NULL),
    ('boh-nme-phe', 'beta-hydroxy-N-Methyl-Phenylalanine', NULL, NULL),
    ('boh-nme-val', 'beta-hydroxy-N-Methyl-Valine', NULL, NULL),
    ('boh-tyr', 'beta-hydroxy-tyrosine', NULL, NULL),
    ('boh-val', 'beta-hydroxyvaline', NULL, NULL),
    ('bome-asp', 'beta-methoxy-aspartic acid', NULL, NULL),
    ('bome-tyr', 'beta-methoxy-tyrosine', NULL, NULL),
    ('bme-asn', 'beta-methyl-asparagine', NULL, NULL),
    ('bme-asp', 'beta-methyl-aspartic acid', NULL, NULL),
    ('bme-br-phe', 'beta-methyl-bromophenylalanine', NULL, NULL),
    ('bme-gln', 'beta-methylglutamine', NULL, NULL),
    ('bme-ile', 'beta-methylisoleucine', NULL, NULL),
    ('btyr', 'beta-tyrosine', NULL, NULL),
    ('bu-ala', 'beta-ureido-dehydroAlanine', NULL, NULL),
    ('bht', 'b-OH-tyrosine', NULL, NULL),
    ('br-phe', 'bromophenylalanine', NULL, NULL),
    ('br-tyr', 'bromotyrosine', NULL, NULL),
    ('butacp', 'Butyryl-ACP', NULL, NULL),
    ('cap', 'capreomycidine', NULL, NULL),
    ('cl-ile', 'Chloro-Isoleucine', NULL, NULL),
    ('cl-nme-tyr', 'Chloro-N-methyl-tyrosine', NULL, NULL),
    ('cl-tyr', 'chloro-tyrosine', NULL, NULL),
    ('cit', 'Citrulline', NULL, NULL),
    ('cma', 'coronamic acid', NULL, NULL),
    ('ck-arg', 'cyclo alpha-ketoarginine', NULL, NULL),
    ('chc', 'Cyclohexylcarbonyl-CoA', NULL, NULL),
    ('cysa', 'cysteic acid', NULL, NULL),
    ('cys', 'Cysteine', 'Cys', 'C'),
    ('d-dab', 'D-2,4-diaminobutyric acid', NULL, NULL),
    ('d-abu', 'D-2-Aminobutyric acid', NULL, NULL),
    ('d-cooh-trp', 'D-2-carboxy-tryptophan', NULL, NULL),
    ('d-hmp', 'D-2-hydroxy-3-methylpentanoic acid', NULL, NULL),
    ('d-hiv', 'D-2-hydroxyisovalerate', NULL, NULL),
    ('d-dhpg', 'D-3,5-dihydroxyphenylglycine', NULL, NULL),
    ('d-br-nme-tyr', 'D-3-bromo-N-methyl-Tyrosine', NULL, NULL),
    ('d-cl-nme-tyr', 'D-3-chloro-N-methyl-Tyrosine', NULL, NULL),
    ('d-i-nme-tyr', 'D-3-iodo-N-methyl-Tyrosine', NULL, NULL),
    ('d-3ome-ala', 'D-3-methoxyalanine', NULL, NULL),
    ('d-f-ph-gly', 'D-4-fluoroPhenylGlycine', NULL, NULL),
    ('d-cl-trp', 'D-6’-chloro-tryptophan', NULL, NULL),
    ('d-cl-conh2-trp', 'D-6-chloro-N2-formamidotryptophan', NULL, NULL),
    ('d-ala', 'D-Alanine', NULL, NULL),
    ('d-aile', 'D-allo-Isoleucine', NULL, NULL),
    ('d-athr', 'D-allo-Threonine', NULL, NULL),
    ('hyv-d', 'D-alpha-hydroxyisovaleric acid', NULL, NULL),
    ('d-arg', 'D-Arginine', NULL, NULL),
    ('d-asn', 'D-Asparagine', NULL, NULL),
    ('d-asp', 'D-aspartic acid', NULL, NULL),
    ('d-n2me-boh-asn', 'D-beta-hydroxy-N2-methyl-asparagine', NULL, NULL),
    ('d-boh-val', 'D-beta-hydroxyvaline', NULL, NULL),
    ('d-bme-asp', 'D-beta-methyl-aspartic acid', NULL, NULL),
    ('d-bme-gln', 'D-beta-methylglutamine', NULL, NULL),
    ('d-bphe', 'D-beta-phenylalanine', NULL, NULL),
    ('d-cit', 'D-Citrulline', NULL, NULL),
    ('d-cysa', 'D-cysteic acid', NULL, NULL),
    ('d-cys', 'D-Cysteine', NULL, NULL),
    ('dv-tyr', 'dehydro vinylogous tyrosine', NULL, NULL),
    ('dh-ala', 'dehydroalanine', NULL, NULL),
    ('dhcys', 'dehydro-cysteine', NULL, NULL),
    ('dpyr', 'dehydropyrrolidone', NULL, NULL),
    ('dht', 'dehydrotyrosine', NULL, NULL),
    ('d-end', 'D-enduracididine', NULL, NULL),
    ('d-fo-oh-orn', 'D-formyl-hydroxyornithine', NULL, NULL),
    ('d-glu', 'D-Glutamic Acid', NULL, NULL),
    ('d-meo-glu', 'D-Glutamic Acid methyl ester', NULL, NULL),
    ('d-gln', 'D-Glutamine', NULL, NULL),
    ('d-har', 'D-homoarginine', NULL, NULL),
    ('d-hpr', 'D-homoproline', NULL, NULL),
    ('d-hse', 'D-Homoserine', NULL, NULL),
    ('dmog', 'DHP-methyloxazolinyl group', NULL, NULL),
    ('d-oh-asn', 'D-HydroxyAsparagine', NULL, NULL),
    ('d-oh-asp', 'D-Hydroxyaspartic acid', NULL, NULL),
    ('d-oh-corn', 'D-Hydroxy-cycloOrnithine', NULL, NULL),
    ('d-hpg', 'D-HydroxyPhenylGlycine', NULL, NULL),
    ('d-4oh-pro', 'D-hydroxyproline', NULL, NULL),
    ('cl2-nme-dhleu', 'di-chloro-N-methyl-dehydroLeucine', NULL, NULL),
    ('cl2-nme-leu', 'di-chloro-N-methyl-Leucine', NULL, NULL),
    ('dhpt', 'dihydroxyphenylthiazol group', NULL, NULL),
    ('d-ile', 'D-Isoleucine', NULL, NULL),
    ('d-ival', 'D-isovaline', NULL, NULL),
    ('d-kyn', 'D-kynurenine', NULL, NULL),
    ('d-lac', 'D-lactic acid', NULL, NULL),
    ('d-leu', 'D-Leucine', NULL, NULL),
    ('d-lys', 'D-Lysine', NULL, NULL),
    ('d-nme-ome-tyr', 'D-N,O-dimethyl-tyrosine', NULL, NULL),
    ('d-n2me-asn', 'D-N2-methyl-asparagine', NULL, NULL),
    ('d-oh-orn', 'D-N5-hydroxyornithine', NULL, NULL),
    ('d-ac-oh-orn', 'D-N-acetyl-hydroxyornithine', NULL, NULL),
    ('d-nfo-ala', 'D-N-formyl-Alanine', NULL, NULL),
    ('d-oh-dhpg', 'D-N-hydroxy-dehydro-HydroxyPhenylGlycine', NULL, NULL),
    ('d-nme-aile', 'D-N-methyl-alloisoleucine', NULL, NULL),
    ('d-nme-leu', 'D-N-methyl-Leucine', NULL, NULL),
    ('d-nme-nva', 'D-N-methyl-norvaline', NULL, NULL),
    ('d-nme-phe', 'D-N-Methyl-Phenylalanine', NULL, NULL),
    ('d-nme-val', 'D-N-Methylvaline', NULL, NULL),
    ('d-nva', 'D-Norvaline', NULL, NULL),
    ('dha', 'docosahexaenoic acid', NULL, NULL),
    ('dil', 'Dolaisoleucine', NULL, NULL),
    ('doe', 'Dolaphenine', NULL, NULL),
    ('dap', 'Dolaproine', NULL, NULL),
    ('dpy', 'Dolapyrrolidone', NULL, NULL),
    ('dov', 'Dolavaline', NULL, NULL),
    ('d-orn', 'D-ornithine', NULL, NULL),
    ('d-phe', 'D-Phenylalanine', NULL, NULL),
    ('d-ph-gly', 'D-PhenylGlycine', NULL, NULL),
    ('d-ph-lac', 'D-Phenyl-lactate', NULL, NULL),
    ('d-po-asn', 'D-PhosphateAsparagine', NULL, NULL),
    ('d-pro', 'D-Proline', NULL, NULL),
    ('d-ser', 'D-Serine', NULL, NULL),
    ('d-t-leu', 'D-tert-Leu', NULL, NULL),
    ('d-thr', 'D-Threonine', NULL, NULL),
    ('d-trp', 'D-Tryptophan', NULL, NULL),
    ('d-tyr', 'D-Tyrosine', NULL, NULL),
    ('d-val', 'D-Valine', NULL, NULL),
    ('end', 'enduracididine', NULL, NULL),
    ('eta', 'Ethanolamine', NULL, NULL),
    ('emal', 'Ethylmalonyl-CoA', NULL, NULL),
    ('redmal', 'fully saturated acyl-S-T (a derivative of malonyl-CoA reduced by ketoreductase, dehydrated by  dehydratase and reduced by enoyl reductase)', NULL, NULL),
    ('redmmal', 'fully saturated methylacyl-S-T (a derivative of methylmalonyl-CoA reduced by ketoreductase, dehydrated by  dehydratase and reduced by enoyl reductase)', NULL, NULL),
    ('redmxmal', 'fully saturated methoxyacyl-S-T (a derivative of methoxymalonyl-CoA reduced by ketoreductase, dehydrated by  dehydratase and reduced by enoyl reductase)', NULL, NULL),
    ('goh-nme-val', 'gama-hydroxy-N-Methyl-Valine', NULL, NULL),
    ('glu', 'Glutamic acid', 'Glu', 'E'),
    ('meo-glu', 'Glutamic Acid methyl ester', NULL, NULL),
    ('gln', 'Glutamine', 'Gln', 'Q'),
    ('gly', 'Glycine', 'Gly', 'G'),
    ('glyc', 'Glycolate', NULL, NULL),
    ('gspd', 'guanylspermidine', NULL, NULL),
    ('hexacp', 'Hexanoyl-ACP', NULL, NULL),
    ('his', 'Histidine', 'His', 'H'),
    ('har', 'homoarginine', NULL, NULL),
    ('hil', 'homoisoleucine', NULL, NULL),
    ('hph', 'Homophenylalanine', NULL, NULL),
    ('hpr', 'homoproline', NULL, NULL),
    ('hse', 'Homoserine', NULL, NULL),
    ('hsel', 'homoserine lactone', NULL, NULL),
    ('hty', 'Homotyrosine', NULL, NULL),
    ('hk-arg', 'hydrated alpha-ketoarginine', NULL, NULL),
    ('oh-pyr', 'hydroxy pyrrolidone', NULL, NULL),
    ('hap', 'hydroxyacetyl propionyl', NULL, NULL),
    ('oh-asn', 'Hydroxyasparagine', NULL, NULL),
    ('oh-asp', 'Hydroxyaspartic acid', NULL, NULL),
    ('oh-blys', 'hydroxy-beta lysine', NULL, NULL),
    ('oh-corn', 'Hydroxy-cycloOrnithine', NULL, NULL),
    ('oh-his', 'Hydroxyhistidine', NULL, NULL),
    ('hip', 'hydroxyisovalerylpropionyl', NULL, NULL),
    ('hxmal', 'Hydroxymalonyl-CoA', NULL, NULL),
    ('hpg', 'HydroxyPhenylGlycine', NULL, NULL),
    ('hpa', 'hydroxypicolinic acid', NULL, NULL),
    ('hysp', 'hydroxysecbutyl acetyl propionyl', NULL, NULL),
    ('isobut', 'Isobutyryl-CoA', NULL, NULL),
    ('ile', 'Isoleucine', 'Ile', 'I'),
    ('ileol', 'Isoleucinol', NULL, NULL),
    ('chri', 'isopyoverdin chromophore', NULL, NULL),
    ('iser', 'isoserine', NULL, NULL),
    ('ist', 'isostatine', NULL, NULL),
    ('iva', 'isovaline', NULL, NULL),
    ('ivalol', 'isovalinol', NULL, NULL),
    ('k-leu', 'keto-Leucine', NULL, NULL),
    ('kyn', 'kynurenine', NULL, NULL),
    ('aco', 'L-acosamine', NULL, NULL),
    ('lac', 'Lactic acid', NULL, NULL),
    ('act', 'L-actinosamine', NULL, NULL),
    ('ere', 'L-eremosamine', NULL, NULL),
    ('leu', 'Leucine', 'Leu', 'L'),
    ('leuol', 'Leucinol', NULL, NULL),
    ('ria', 'L-ristosamine', NULL, NULL),
    ('lys', 'Lysine', 'Lys', 'K'),
    ('mal', 'Malonyl-CoA', NULL, NULL),
    ('met', 'Methionine', 'Met', 'M'),
    ('o2-met', 'Methionine sulfone', NULL, NULL),
    ('o-met', 'Methionine-S-oxide', NULL, NULL),
    ('ome-asp', 'methoxyaspartic acid', NULL, NULL),
    ('mxmal', 'Methoxymalonyl-CoA', NULL, NULL),
    ('ome-trp', 'methoxytryptophan', NULL, NULL),
    ('me-aoa', 'methyl-2-aminooctanoic acid', NULL, NULL),
    ('mmal', 'Methylmalonyl-CoA', NULL, NULL),
    ('meox-ile', 'methyloxazoline-isoleucine', NULL, NULL),
    ('mpro', 'methylproline', NULL, NULL),
    ('myc', 'Mycolate', NULL, NULL),
    ('nme-bme-leu', 'N,beta-dimethylLeucine', NULL, NULL),
    ('dime-aile', 'N,gamma-alloisoleucine', NULL, NULL),
    ('nme-ome-ile', 'N,O-dimethyl-isoleucine', NULL, NULL),
    ('nme-ome-tyr', 'N,O-dimethyl-tyrosine', NULL, NULL),
    ('nme-ome-tyrc', 'N,O-dimethyl-tyrosinecarboxamid', NULL, NULL),
    ('dime-cys', 'N,S-dimethylcysteine', NULL, NULL),
    ('nac-dpr', 'N1-acetyl-2,3-Diaminopropionic acid', NULL, NULL),
    ('n1-cooh-bhtrp', 'N1-carboxy-bichomotryptophan', NULL, NULL),
    ('nfo-dpr', 'N1-formyl-2,3-Diaminopropionic acid', NULL, NULL),
    ('1me-trp', 'N1-methyl-tryptophan', NULL, NULL),
    ('oh-orn', 'N5-hydroxy ornithine', NULL, NULL),
    ('fo-oh-orn', 'N6-formyl-hydroxyornithine', NULL, NULL),
    ('ac-aib', 'N-Acetyl-2-aminoisobutyric acid', NULL, NULL),
    ('ac-oh-orn', 'N-acetyl-hydroxyornithine', NULL, NULL),
    ('ac-ival', 'N-acetyl-isovaline', NULL, NULL),
    ('nac-leu', 'N-acetyl-Leucine', NULL, NULL),
    ('nac-fo-oh-orn', 'N-acetyl-N6-formyl-N6-hydroxyornithine', NULL, NULL),
    ('ac-phe', 'N-acetylphenylalanine', NULL, NULL),
    ('ac-trp', 'N-acetyltryptophan', NULL, NULL),
    ('ac-val', 'N-Acetylvaline', NULL, NULL),
    ('ddil', 'N-desmethyldolaisoleuine', NULL, NULL),
    ('ndme-ala', 'N-dimethyl-Alanine', NULL, NULL),
    ('ndme-leu', 'N-dimethyl-leucine', NULL, NULL),
    ('nfo-ala', 'N-formyl-Alanine', NULL, NULL),
    ('nfo-d-abu', 'N-formyl-D-aminobyric acid', NULL, NULL),
    ('nfo-gln', 'N-formyl-Glutamine', NULL, NULL),
    ('nfo-ile', 'N-formyl-Isoleucine', NULL, NULL),
    ('nfo-iser', 'N-formyl-isoserine', NULL, NULL),
    ('nfo-leu', 'N-formyl-Leucine', NULL, NULL),
    ('nfo-pro', 'N-Formyl-Proline', NULL, NULL),
    ('nfo-val', 'N-formyl-Valine', NULL, NULL),
    ('oh-dhpg', 'N-hydroxy-dehydro-HydroxyPhenylGlycine', NULL, NULL),
    ('n-oh-hta', 'N-Hydroxy-histamine', NULL, NULL),
    ('nome-ac-d-phe', 'N-methoxyacetyl-D-phenylalanine', NULL, NULL),
    ('nome-ac-val', 'N-methoxyacetyl-valine', NULL, NULL),
    ('nme-hv-val', 'N-methyl homo vinylogous Valine', NULL, NULL),
    ('nme-dphe', 'N-methyl-2,3-dehydrophenylalanine', NULL, NULL),
    ('nme-br-trp', 'N-methyl-2-Bromo-tryptophan', NULL, NULL),
    ('nme-bmt', 'N-methyl-4-butenyl-4-methyl threonine', NULL, NULL),
    ('nme-me2a-phe', 'N-methyl-4-dimethylamino-phenylalanine', NULL, NULL),
    ('nme-mea-phe', 'N-methyl-4-methylamino-phenylalanine', NULL, NULL),
    ('nme-oh-trp', 'N-methyl-5-hydroxytryptophan', NULL, NULL),
    ('nme-cl-oh-trp', 'N-methyl-6-chloro-5-hydroxytryptophan', NULL, NULL),
    ('nme-cl-trp', 'N-methyl-6-chloro-tryptophan', NULL, NULL),
    ('nme-ala', 'N-Methyl-Alanine', NULL, NULL),
    ('nme-aile', 'N-methyl-alloIsoleucine', NULL, NULL),
    ('nme-asn', 'N-methylasparagine', NULL, NULL),
    ('nme-bala', 'N-methyl-beta-alanine', NULL, NULL),
    ('mcp', 'N-methylchloropyrrole', NULL, NULL),
    ('nme-cys', 'N-methylcysteine', NULL, NULL),
    ('nme-dha', 'N-Methyl-dehydroalanine', NULL, NULL),
    ('mdcp', 'N-methyldichloropyrrole-2-carboxylic acid', NULL, NULL),
    ('d-nme-ser', 'N-Methyl-D-Serine', NULL, NULL),
    ('nme-gln', 'N-methylglutamine', NULL, NULL),
    ('nme-gly', 'N-Methyl-Glycine', NULL, NULL),
    ('nme-gly-thz', 'N-Methyl-Glycine-thiazole', NULL, NULL),
    ('nme-hty', 'N-methyl-homotyrosine', NULL, NULL),
    ('nme-oh-ile', 'N-methyl-hydroxyisoleucine', NULL, NULL),
    ('nme-hpg', 'N-methyl-HydroxyPhenylGlycine', NULL, NULL),
    ('nme-ile', 'N-Methyl-Isoleucine', NULL, NULL),
    ('nme-leu', 'N-Methyl-Leucine', NULL, NULL),
    ('nme-phe', 'N-Methyl-Phenylalanine', NULL, NULL),
    ('nme-ph-gly', 'N-methyl-phenylglycine', NULL, NULL),
    ('nme-ser', 'N-Methyl-Serine', NULL, NULL),
    ('nme-thr', 'N-methylthreonine', NULL, NULL),
    ('nme-tyr', 'N-methyltyrosine', NULL, NULL),
    ('nme-val', 'N-Methyl-Valine', NULL, NULL),
    ('norcma', 'norcoronamic acid', NULL, NULL),
    ('nspd', 'norspermidine', NULL, NULL),
    ('nst', 'norstatine', NULL, NULL),
    ('nva', 'Norvaline', NULL, NULL),
    ('ntme-leu', 'N-trimethyl-leucine', NULL, NULL),
    ('oac-leuol', 'O-acetyl-leucinol', NULL, NULL),
    ('ac-ser', 'O-acetyl-Serine', NULL, NULL),
    ('ddap', 'O-desmethyldolaproine', NULL, NULL),
    ('ome-thr', 'O-methyl-threonine', NULL, NULL),
    ('orn', 'Ornithine', NULL, NULL),
    ('osu-hmp', 'O-sulfate-2-hydroxy-3-methylpentanoic acid', NULL, NULL),
    ('other', 'Other', NULL, NULL),
    ('ambenz', 'p-Aminobenzoate', NULL, NULL),
    ('poh-bz', 'para-hydroxy-benzoic acid', NULL, NULL),
    ('coum', 'p-Coumaroyl-CoA', NULL, NULL),
    ('pda', 'pentanedioic acid', NULL, NULL),
    ('pha', 'phenylacetic acid', NULL, NULL),
    ('phe', 'Phenylalanine', 'Phe', 'F'),
    ('pheol', 'phenylalaninol', NULL, NULL),
    ('pgly', 'phenylglycine', NULL, NULL),
    ('ph-lac', 'Phenyl-lactate', NULL, NULL),
    ('ph-ser', 'phenylserine', NULL, NULL),
    ('pt', 'phosphinothricin', NULL, NULL),
    ('ptrp', 'phototryptophan', NULL, NULL),
    ('pico', 'picolinic acid', NULL, NULL),
    ('pip', 'pipecolate', NULL, NULL),
    ('nbenz', 'p-Nitrobenzoate', NULL, NULL),
    ('pro', 'Proline', 'Pro', 'P'),
    ('proc', 'proline carboxamid', NULL, NULL),
    ('paoa', 'propenoyl-2-aminobutanoyloxazole acid', NULL, NULL),
    ('paloa', 'propenoyl-alanyloxazole acid', NULL, NULL),
    ('pmst', 'propenoyl-O-methylserinylthiazole acid', NULL, NULL),
    ('prop-coa', 'Propionyl-CoA', NULL, NULL),
    ('put', 'putrescine', NULL, NULL),
    ('chrp', 'pyoverdin chromophore', NULL, NULL),
    ('pglu', 'pyroglutamic acid', NULL, NULL),
    ('pyr', 'pyrrolidone', NULL, NULL),
    ('pya', 'pyruvate', NULL, NULL),
    ('sal', 'salicylate', NULL, NULL),
    ('ser', 'Serine', 'Ser', 'S'),
    ('serol', 'Serinol', NULL, NULL),
    ('spd', 'spermidine', NULL, NULL),
    ('sta', 'statine', NULL, NULL),
    ('t-leu', 'tert-Leu', NULL, NULL),
    ('phe-thz', 'thiazolylphenylalanine', NULL, NULL),
    ('thr', 'Threonine', 'Thr', 'T'),
    ('tcpda', 'Trans-cyclopentane-(1R, 2R)-dicarboxylic acid', NULL, NULL),
    ('cl3-2oh-nme-leu', 'tri-chloro-2-hydroxy-N-methyl-Leucine', NULL, NULL),
    ('cl3-5oh-nme-leu', 'tri-chloro-5-hydroxy-N-methyl-Leucine', NULL, NULL),
    ('cl3-nme-dhleu', 'tri-chloro-N-methyl-dehydroLeucine', NULL, NULL),
    ('cl3-nme-leu', 'tri-chloro-N-methyl-Leucine', NULL, NULL),
    ('trp', 'Tryptophan', 'Trp', 'W'),
    ('trpol', 'tryptophanol', NULL, NULL),
    ('tyr', 'Tyrosine', 'Tyr', 'Y'),
    ('nrp', 'undefined nonribosomal peptide monomer', NULL, NULL),
    ('pk', 'undefined polyketide monomer', NULL, NULL),
    ('val', 'Valine', 'Val', 'V'),
    ('valol', 'valinol', NULL, NULL),
    ('v-arg', 'vinylogous arginine', NULL, NULL),
    ('v-oh-tyr', 'vinylogous hydroxy tyrosine', NULL, NULL),
    ('v-tyr', 'vinylogous tyrosine', NULL, NULL),
    ('boh-phe', 'beta-hydroxy-phenylalanine', NULL, NULL),
    ('boh-ome-tyr', 'beta-hydroxy-omethyl-tyr', NULL, NULL),
    ('aoh-gly', 'alpha-hydroxy-gly', NULL, NULL),
    ('boh-d-leu', 'beta-hydroxy-d-leucine', NULL, NULL),
    ('33p-l-ala', '3-(3-pyridyl)-l-alanine', NULL, NULL),
    ('goh-val', 'gamma-hydroxy-valine', NULL, NULL),
    ('fhorn', 'N6-formyl-hydroxyornithine', NULL, NULL),
    ('dhb-al', '2,3-dihydroxybenzoic acid-amp-ligase', NULL, NULL),
    ('sal-al', 'salicylate-amp-ligase', NULL, NULL),
    ('noh-d-ala', 'n-hydroxil-d-alanine', NULL, NULL),
    ('3oh-3me-pro', '3-hydroxy-3-methyl-proline', NULL, NULL),
    ('noh-val', 'n-hydroxy-l-valine', NULL, NULL),
    ('4oh5oh-orn', '4.5-dihydroxyornithine', NULL, NULL),
    ('4oh5oh-hty', '4.5-dihydroxyhomotyrosine', NULL, NULL),
    ('3oh-glu', '3-hydroxyglutamine', NULL, NULL),
    ('3oh-4me-pro', '3-hydroxy-4-methylproline', NULL, NULL),
    ('delta-but', 'delta-butyric acid', NULL, NULL),
    ('4hpg', '4-Hydroxyphenylglycine', NULL, NULL),
    ('glycy', 'glycocyamine', NULL, NULL),
    ('4ap2c', '4-acetamidopyrrole-2-carboxylate', NULL, NULL),
    ('doh-hda', 'Dihydroxy-hexadecanoic-acid', NULL, NULL),
    ('lys-erg', 'D-lysergig acid', NULL, NULL),
    ('hyv', 'alpha-hydroxyisovaleric acid', NULL, NULL),
    ('val-vol', 'valinol', NULL, NULL),
    ('asp-me', 'methyl-aspartic acid', NULL, NULL),
    ('orn-fN5H', 'N5-hydroxyornithine', NULL, NULL),
    ('phe-ac', 'N-acetylphenylalanine', NULL, NULL);
