CREATE TABLE antismash.smcogs (
    smcog_id	serial NOT NULL,
    name	text,
    description	text,
    functional_class	int4,
    CONSTRAINT smcogs_pkey PRIMARY KEY (smcog_id),
    CONSTRAINT smcogs_functional_class_fkey FOREIGN KEY (functional_class) REFERENCES antismash.functional_classes (functional_class_id)
);
COMMENT ON TABLE antismash.smcogs IS
  'Secondary Metabolite specific Clusters of Orthologous Groups (smCoGs)';


INSERT INTO antismash.smcogs (name, description, functional_class)
SELECT val.name, val.description, f.functional_class_id
FROM (
    VALUES
        ('SMCOG1000', 'ABC transporter ATP-binding protein', 'transporter'),
        ('SMCOG1001', 'short-chain dehydrogenase/reductase SDR', 'smcog_derived'),
        ('SMCOG1002', 'AMP-dependent synthetase and ligase', 'smcog_derived'),
        ('SMCOG1003', 'sensor histidine kinase', 'regulator'),
        ('SMCOG1004', 'thioesterase', 'smcog_derived'),
        ('SMCOG1005', 'Drug resistance transporter, EmrB/QacA', 'transporter'),
        ('SMCOG1006', 'acyl-CoA dehydrogenase', 'smcog_derived'),
        ('SMCOG1007', 'cytochrome P450', 'smcog_derived'),
        ('SMCOG1008', 'response regulator', 'regulator'),
        ('SMCOG1009', 'mbtH-like protein', 'smcog_derived'),
        ('SMCOG1010', 'NAD-dependent epimerase/dehydratase', 'smcog_derived'),
        ('SMCOG1011', 'transport system permease protein', 'transporter'),
        ('SMCOG1012', '4''-phosphopantetheinyl transferase', 'smcog_derived'),
        ('SMCOG1013', 'aminotransferase class-III', 'smcog_derived'),
        ('SMCOG1014', 'LysR family transcriptional regulator', 'regulator'),
        ('SMCOG1015', 'AraC family transcriptional regulator', 'regulator'),
        ('SMCOG1016', 'LuxR family DNA-binding response regulator', 'regulator'),
        ('SMCOG1017', 'aldehyde dehydrogenase', 'smcog_derived'),
        ('SMCOG1018', 'isochorismate synthase', 'smcog_derived'),
        ('SMCOG1019', 'aminotransferase', 'smcog_derived'),
        ('SMCOG1020', 'major facilitator transporter', 'transporter'),
        ('SMCOG1021', 'malonyl CoA-acyl carrier protein transacylase', 'smcog_derived'),
        ('SMCOG1022', 'Beta-ketoacyl synthase', 'smcog_derived'),
        ('SMCOG1023', 'enoyl-CoA hydratase', 'smcog_derived'),
        ('SMCOG1024', 'chalcone and stilbene synthase domain protein', 'smcog_derived'),
        ('SMCOG1025', 'diguanylate cyclase', 'smcog_derived'),
        ('SMCOG1026', 'transposase', 'other'),
        ('SMCOG1027', 'isochorismatase', 'smcog_derived'),
        ('SMCOG1028', 'crotonyl-CoA reductase / alcohol', 'dehydrogenase'),
        ('SMCOG1029', 'RND family efflux transporter MFP subunit', 'transporter'),
        ('SMCOG1030', 'serine/threonine protein kinase', 'regulator'),
        ('SMCOG1031', 'LysR family transcriptional regulator', 'regulator'),
        ('SMCOG1032', 'RNA polymerase, sigma-24 subunit, ECF subfamily', 'regulator'),
        ('SMCOG1033', 'iron compound ABC transporter, periplasmic', 'transporter'),
        ('SMCOG1034', 'cytochrome P450', 'smcog_derived'),
        ('SMCOG1035', 'MMPL domain-containing transport protein', 'smcog_derived'),
        ('SMCOG1036', 'alpha/beta hydrolase fold protein', 'smcog_derived'),
        ('SMCOG1037', 'heavy metal translocating P-type ATPase', 'other'),
        ('SMCOG1038', 'phenylalanine-specific permease', 'smcog_derived'),
        ('SMCOG1039', 'aldo/keto reductase family oxidoreductase', 'smcog_derived'),
        ('SMCOG1040', 'alcohol dehydrogenase', 'smcog_derived'),
        ('SMCOG1041', 'transcriptional regulator, SARP family', 'regulator'),
        ('SMCOG1042', 'O-methyltransferase', 'smcog_derived'),
        ('SMCOG1043', 'hydroxymethylglutaryl-CoA synthase', 'smcog_derived'),
        ('SMCOG1044', 'ABC transporter, permease protein', 'transporter'),
        ('SMCOG1045', 'glycosyl transferase group 1', 'smcog_derived'),
        ('SMCOG1046', 'Dioxygenase TauD/TfdA', 'smcog_derived'),
        ('SMCOG1047', 'phosphopantetheine-binding domain-containing protein', 'smcog_derived'),
        ('SMCOG1048', 'sensor histidine kinase', 'regulator'),
        ('SMCOG1049', 'AcrB/AcrD/AcrF family protein', 'transporter'),
        ('SMCOG1050', 'monooxygenase FAD-binding', 'smcog_derived'),
        ('SMCOG1051', 'TonB-dependent siderophore receptor', 'transporter'),
        ('SMCOG1052', 'Terpene synthase/cyclase metal-binding domain protein', 'smcog_derived'),
        ('SMCOG1053', 'beta-lactamase', 'smcog_derived'),
        ('SMCOG1054', 'hypothetical protein', 'other'),
        ('SMCOG1055', 'pyruvate oxidase/decarboxylase', 'smcog_derived'),
        ('SMCOG1056', 'DegT/DnrJ/EryC1/StrS aminotransferase', 'smcog_derived'),
        ('SMCOG1057', 'TetR family transcriptional regulator', 'regulator'),
        ('SMCOG1058', 'ArsR family transcriptional regulator', 'regulator'),
        ('SMCOG1059', 'acetyl-CoA carboxylase, carboxyl transferase,', 'smcog_derived'),
        ('SMCOG1060', '4''-phosphopantetheinyl transferase', 'smcog_derived'),
        ('SMCOG1061', 'methyl-accepting chemotaxis protein', 'other'),
        ('SMCOG1062', 'glycosyltransferase, MGT family', 'smcog_derived'),
        ('SMCOG1063', 'argininosuccinate lyase/adenylosuccinate lyase', 'smcog_derived'),
        ('SMCOG1064', 'glucose-1-phosphate adenylyl/thymidylyltransferase', 'smcog_derived'),
        ('SMCOG1065', 'ABC-2 type transporter', 'transporter'),
        ('SMCOG1066', 'alpha/beta hydrolase domain-containing protein', 'smcog_derived'),
        ('SMCOG1067', 'putative ABC transporter permease protein', 'transporter'),
        ('SMCOG1068', 'extracellular solute-binding protein family 5', 'transporter'),
        ('SMCOG1069', 'putative ABC transporter permease protein', 'transporter'),
        ('SMCOG1070', 'lanthionine synthetase C family protein', 'smcog_derived'),
        ('SMCOG1071', 'GntR family transcriptional regulator', 'regulator'),
        ('SMCOG1072', 'dehydrogenase', 'smcog_derived'),
        ('SMCOG1073', 'PE-PGRS family protein', 'other'),
        ('SMCOG1074', 'major facilitator family transporter', 'transporter'),
        ('SMCOG1075', 'alkaline serine protease, subtilase family', 'smcog_derived'),
        ('SMCOG1076', 'RND efflux system, outer membrane lipoprotein,', 'transporter'),
        ('SMCOG1077', 'phage integrase family protein', 'other'),
        ('SMCOG1078', 'LacI family transcription regulator', 'regulator'),
        ('SMCOG1079', 'oxidoreductase', 'smcog_derived'),
        ('SMCOG1080', 'lysine/ornithine N-monooxygenase', 'smcog_derived'),
        ('SMCOG1081', 'cysteine synthase', 'smcog_derived'),
        ('SMCOG1082', 'TonB-dependent siderophore receptor family', 'transporter'),
        ('SMCOG1083', 'oxidoreductase', 'smcog_derived'),
        ('SMCOG1084', '3-oxoacyl-(acyl carrier protein) synthase III', 'smcog_derived'),
        ('SMCOG1085', 'binding-protein-dependent transport systems', 'transporter'),
        ('SMCOG1086', 'MATE efflux family protein', 'transporter'),
        ('SMCOG1087', 'hypothetical protein', 'other'),
        ('SMCOG1088', 'acyltransferase 3', 'smcog_derived'),
        ('SMCOG1089', 'methyltransferase', 'smcog_derived'),
        ('SMCOG1090', 'acetyl-CoA carboxylase biotin carboxylase', 'smcog_derived'),
        ('SMCOG1091', 'glutamine-binding lipoprotein glnH', 'smcog_derived'),
        ('SMCOG1092', 'hypothetical protein', 'other'),
        ('SMCOG1093', 'Beta-ketoacyl synthase', 'smcog_derived'),
        ('SMCOG1094', 'ferredoxin', 'other'),
        ('SMCOG1095', '3-hydroxybutyryl-CoA dehydrogenase', 'smcog_derived'),
        ('SMCOG1096', 'polar amino acid ABC transporter, inner membrane', 'transporter'),
        ('SMCOG1097', 'transposase', 'other'),
        ('SMCOG1098', 'enterobactin/ferric enterobactin esterase', 'smcog_derived'),
        ('SMCOG1099', 'hypothetical protein', 'other'),
        ('SMCOG1100', '3-hydroxyisobutyrate dehydrogenase', 'smcog_derived'),
        ('SMCOG1101', 'phosphoglycerate mutase', 'smcog_derived'),
        ('SMCOG1102', 'glycosyltransferase', 'smcog_derived'),
        ('SMCOG1103', 'FAD dependent oxidoreductase', 'smcog_derived'),
        ('SMCOG1104', 'putative esterase', 'smcog_derived'),
        ('SMCOG1105', 'amidase', 'smcog_derived'),
        ('SMCOG1106', 'major facilitator transporter', 'transporter'),
        ('SMCOG1107', 'TonB-dependent receptor', 'transporter'),
        ('SMCOG1108', 'ROK family protein', 'other'),
        ('SMCOG1109', '8-amino-7-oxononanoate synthase', 'smcog_derived'),
        ('SMCOG1110', '1-deoxy-D-xylulose-5-phosphate synthase', 'smcog_derived'),
        ('SMCOG1111', 'GCN5-related N-acetyltransferase', 'smcog_derived'),
        ('SMCOG1112', 'sigma-54 dependent trancsriptional regulator', 'regulator'),
        ('SMCOG1113', 'inner-membrane translocator', 'transporter'),
        ('SMCOG1114', 'ornithine carbamoyltransferase', 'smcog_derived'),
        ('SMCOG1115', 'HAD-superfamily hydrolase, subfamily IA, variant', 'smcog_derived'),
        ('SMCOG1116', 'Homoserine/threonine efflux protein', 'transporter'),
        ('SMCOG1117', 'sodium/hydrogen exchanger', 'transporter'),
        ('SMCOG1118', 'binding-protein-dependent transport systems', 'transporter'),
        ('SMCOG1119', 'halogenase', 'smcog_derived'),
        ('SMCOG1120', 'AsnC family transcriptional regulator', 'regulator'),
        ('SMCOG1121', 'dioxygenase, TauD/TfdA', 'smcog_derived'),
        ('SMCOG1122', 'ATP-dependent RNA helicase', 'other'),
        ('SMCOG1123', 'polyprenol-monophosphomannose synthase ppm1', 'smcog_derived'),
        ('SMCOG1124', 'acetyl-CoA acetyltransferase', 'smcog_derived'),
        ('SMCOG1125', 'LysR family transcriptional regulator', 'regulator'),
        ('SMCOG1126', 'extracytoplasmic-function sigma-70 factor', 'regulator'),
        ('SMCOG1127', 'condensation domain-containing protein', 'smcog_derived'),
        ('SMCOG1128', 'cyclase/dehydrase', 'smcog_derived'),
        ('SMCOG1129', 'acyl carrier protein', 'smcog_derived'),
        ('SMCOG1130', 'transposase', 'other'),
        ('SMCOG1131', 'major facilitator transporter', 'transporter'),
        ('SMCOG1132', 'DNA-binding protein HU 1', 'other'),
        ('SMCOG1133', 'Transcription regulator, crp', 'regulator'),
        ('SMCOG1134', 'flavodoxin', 'smcog_derived'),
        ('SMCOG1135', 'MarR family transcriptional regulator', 'regulator'),
        ('SMCOG1136', 'GntR family transcriptional regulator', 'regulator'),
        ('SMCOG1137', 'Major facilitator superfamily MFS 1', 'transporter'),
        ('SMCOG1138', 'FAD linked oxidase domain protein', 'smcog_derived'),
        ('SMCOG1139', 'aminotransferase class V', 'smcog_derived'),
        ('SMCOG1140', 'Lanthionine synthetase C family protein', 'smcog_derived'),
        ('SMCOG1141', 'acyltransferase', 'smcog_derived'),
        ('SMCOG1142', 'PPE family protein', 'other'),
        ('SMCOG1143', 'sugar-binding lipoprotein', 'smcog_derived'),
        ('SMCOG1144', 'thioesterase superfamily protein', 'smcog_derived'),
        ('SMCOG1145', 'Glucose-specific phosphotransferase enzyme IIA', 'smcog_derived'),
        ('SMCOG1146', 'sugar transferase', 'smcog_derived'),
        ('SMCOG1147', 'putative acyl carrier protein', 'smcog_derived'),
        ('SMCOG1148', 'hypothetical protein', 'other'),
        ('SMCOG1149', 'LuxR family transcriptional regulator', 'regulator'),
        ('SMCOG1150', 'isoprenylcysteine carboxyl methyltransferase', 'smcog_derived'),
        ('SMCOG1151', 'transposase', 'other'),
        ('SMCOG1152', 'nucleotide sugar dehydrogenase', 'smcog_derived'),
        ('SMCOG1153', 'Amino acid carrier protein', 'smcog_derived'),
        ('SMCOG1154', 'Pseudouridine synthase', 'smcog_derived'),
        ('SMCOG1155', 'Lantibiotic dehydratase domain protein', 'smcog_derived'),
        ('SMCOG1156', 'Chloramphenicol acetyltransferase', 'smcog_derived'),
        ('SMCOG1157', 'hypothetical protein', 'other'),
        ('SMCOG1158', 'ornithine cyclodeaminase', 'smcog_derived'),
        ('SMCOG1159', 'dihydropteridine reductase', 'smcog_derived'),
        ('SMCOG1160', 'flavin reductase domain protein FMN-binding', 'smcog_derived'),
        ('SMCOG1161', 'oxidoreductase', 'smcog_derived'),
        ('SMCOG1162', 'threonyl-tRNA synthetase', 'other'),
        ('SMCOG1163', 'rhodanese domain-containing protein', 'smcog_derived'),
        ('SMCOG1164', 'transposase IS3/IS911 family protein', 'other'),
        ('SMCOG1165', 'carboxylate-amine ligase', 'smcog_derived'),
        ('SMCOG1166', 'transporter, EamA family', 'transporter'),
        ('SMCOG1167', 'transcriptional regulator', 'regulator'),
        ('SMCOG1168', 'O-succinylhomoserine sulfhydrylase', 'smcog_derived'),
        ('SMCOG1169', 'sugar transport protein', 'transporter'),
        ('SMCOG1170', 'metallo-beta-lactamase family protein', 'smcog_derived'),
        ('SMCOG1171', 'transcriptional regulator, MerR family', 'regulator'),
        ('SMCOG1172', 'methionine aminopeptidase', 'smcog_derived'),
        ('SMCOG1173', 'WD-40 repeat-containing protein', 'other'),
        ('SMCOG1174', 'acetylglutamate kinase', 'smcog_derived'),
        ('SMCOG1175', 'pyridine nucleotide-disulfide oxidoreductase', 'smcog_derived'),
        ('SMCOG1176', 'alkyl hydroperoxide reductase subunit', 'smcog_derived'),
        ('SMCOG1177', 'asparagine synthase (glutamine-hydrolyzing)', 'smcog_derived'),
        ('SMCOG1178', 'cobalamin synthesis protein/P47K family protein', 'smcog_derived'),
        ('SMCOG1179', 'hydrolase', 'smcog_derived'),
        ('SMCOG1180', 'Decarboxylase, pyridoxal-dependent', 'smcog_derived'),
        ('SMCOG1181', 'dehydrogenase', 'smcog_derived'),
        ('SMCOG1182', 'Polyprenyl synthetase', 'smcog_derived'),
        ('SMCOG1183', '3-dehydroquinate synthase', 'smcog_derived'),
        ('SMCOG1184', 'major facilitator transporter', 'transporter'),
        ('SMCOG1185', 'carbon starvation protein A', 'other'),
        ('SMCOG1186', 'polysaccharide export protein', 'transporter'),
        ('SMCOG1187', 'hydroxymethylglutaryl-CoA reductase', 'smcog_derived'),
        ('SMCOG1188', 'hypothetical protein', 'other'),
        ('SMCOG1189', 'L-carnitine dehydratase/bile acid-inducible', 'smcog_derived'),
        ('SMCOG1190', 'GTP-binding protein LepA', 'smcog_derived'),
        ('SMCOG1191', 'acyl-CoA dehydrogenase type 2', 'smcog_derived'),
        ('SMCOG1192', 'transposase', 'other'),
        ('SMCOG1193', 'glutathione S-transferase', 'smcog_derived'),
        ('SMCOG1194', 'DNA polymerase III subunit alpha', 'other'),
        ('SMCOG1195', 'IclR family transcriptional regulator', 'regulator'),
        ('SMCOG1196', 'alkyl hydroperoxide reductase/ Thiol specific', 'smcog_derived'),
        ('SMCOG1197', 'autoinducer-binding transcriptional regulator,', 'regulator'),
        ('SMCOG1198', 'hypothetical protein', 'other'),
        ('SMCOG1199', 'NmrA family protein', 'other'),
        ('SMCOG1200', 'vibriobactin utilization protein ViuB', 'other'),
        ('SMCOG1201', 'response regulator', 'regulator'),
        ('SMCOG1202', 'major facilitator transporter', 'transporter'),
        ('SMCOG1203', 'putative siderophore biosynthesis protein', 'smcog_derived'),
        ('SMCOG1204', 'transketolase', 'smcog_derived'),
        ('SMCOG1205', 'ABC transporter, carbohydrate uptake', 'transporter'),
        ('SMCOG1206', 'transposase', 'other'),
        ('SMCOG1207', 'inositol monophosphatase', 'smcog_derived'),
        ('SMCOG1208', 'pirin domain-containing protein', 'other'),
        ('SMCOG1209', 'polyketide synthase associated protein papA3', 'smcog_derived'),
        ('SMCOG1210', 'glycerol kinase', 'smcog_derived'),
        ('SMCOG1211', 'hypothetical protein', 'other'),
        ('SMCOG1212', 'sodium:dicarboxylate symporter', 'transporter'),
        ('SMCOG1213', 'transposase', 'other'),
        ('SMCOG1214', 'binding-protein-dependent transport systems', 'transporter'),
        ('SMCOG1215', 'TetR family transcriptional regulator', 'regulator'),
        ('SMCOG1216', 'exopolysaccharide biosynthesis domain protein', 'smcog_derived'),
        ('SMCOG1217', 'NADH:flavin oxidoreductase/NADH oxidase', 'smcog_derived'),
        ('SMCOG1218', 'Exonuclease', 'other'),
        ('SMCOG1219', 'N-acetyl-gamma-glutamyl-phosphate reductase', 'smcog_derived'),
        ('SMCOG1220', 'bifunctional ornithine', 'smcog_derived'),
        ('SMCOG1221', 'hypothetical protein', 'other'),
        ('SMCOG1222', 'dehydrogenase', 'smcog_derived'),
        ('SMCOG1223', 'ATPase', 'other'),
        ('SMCOG1224', 'TetR family transcriptional regulator', 'regulator'),
        ('SMCOG1225', 'Polyketide synthesis cyclase', 'smcog_derived'),
        ('SMCOG1226', 'hypothetical protein', 'other'),
        ('SMCOG1227', 'ribosome biogenesis GTP-binding protein YsxC', 'other'),
        ('SMCOG1228', 'methionyl-tRNA formyltransferase', 'smcog_derived'),
        ('SMCOG1229', 'transposase', 'other'),
        ('SMCOG1230', 'Nuclease SbcCD, D subunit', 'other'),
        ('SMCOG1231', 'carboxyvinyl-carboxyphosphonate', 'smcog_derived'),
        ('SMCOG1232', 'hypothetical protein', 'other'),
        ('SMCOG1233', 'disulfide isomerase/thiol-disulfide oxidase', 'smcog_derived'),
        ('SMCOG1234', 'transporter, small conductance mechanosensitive', 'transporter'),
        ('SMCOG1235', 'polysaccharide deacetylase', 'smcog_derived'),
        ('SMCOG1236', 'integral membrane indolylacetylinositol', 'smcog_derived'),
        ('SMCOG1237', 'transposase', 'other'),
        ('SMCOG1238', 'transposase', 'other'),
        ('SMCOG1239', 'TetR family transcriptional regulator', 'regulator'),
        ('SMCOG1240', 'riboflavin biosynthesis protein RibD', 'smcog_derived'),
        ('SMCOG1241', 'lipoprotein dsbF', 'other'),
        ('SMCOG1242', 'transposase', 'other'),
        ('SMCOG1243', 'ABC transporter, permease component', 'transporter'),
        ('SMCOG1244', 'amidohydrolase', 'smcog_derived'),
        ('SMCOG1245', 'ABC transporter protein, integral membrane', 'other'),
        ('SMCOG1246', 'monooxygenase FAD-binding', 'smcog_derived'),
        ('SMCOG1247', 'acetylornithine deacetylase', 'smcog_derived'),
        ('SMCOG1248', 'methyltransferase', 'smcog_derived'),
        ('SMCOG1249', 'carbamoyl phosphate synthase small subunit', 'smcog_derived'),
        ('SMCOG1250', 'DinB', 'other'),
        ('SMCOG1251', 'luciferase family protein', 'other'),
        ('SMCOG1252', 'cation ABC transporter, periplasmic', 'transporter'),
        ('SMCOG1253', 'putative lipoprotein', 'other'),
        ('SMCOG1254', 'ferric enterobactin transport protein FepE', 'transporter'),
        ('SMCOG1255', 'cold-shock DNA-binding domain protein', 'regulator'),
        ('SMCOG1256', 'FkbH like protein', 'smcog_derived'),
        ('SMCOG1257', 'Alpha-glucosidase', 'smcog_derived'),
        ('SMCOG1258', 'Antibiotic biosynthesis monooxygenase', 'smcog_derived'),
        ('SMCOG1259', 'hypothetical protein', 'other'),
        ('SMCOG1260', 'AraC family transcriptional regulator', 'regulator'),
        ('SMCOG1261', 'hypothetical protein', 'other'),
        ('SMCOG1262', 'haloalkane dehalogenase', 'smcog_derived'),
        ('SMCOG1263', 'cobaltochelatase subunit CobN', 'smcog_derived'),
        ('SMCOG1264', 'diaminopimelate decarboxylase', 'smcog_derived'),
        ('SMCOG1265', 'ferredoxin', 'other'),
        ('SMCOG1266', 'hydrogen peroxide sensitive repressor', 'regulator'),
        ('SMCOG1267', 'hypothetical protein', 'other'),
        ('SMCOG1268', 'mandelate racemase/muconate lactonizing enzyme', 'smcog_derived'),
        ('SMCOG1269', 'hypothetical protein', 'other'),
        ('SMCOG1270', 'UDP-3-O-[3-hydroxymyristoyl] N-acetylglucosamine', 'smcog_derived'),
        ('SMCOG1271', '2-isopropylmalate synthase', 'smcog_derived'),
        ('SMCOG1272', 'TPR repeat-containing protein', 'other'),
        ('SMCOG1273', 'hypothetical protein', 'other'),
        ('SMCOG1274', 'gamma-glutamyltranspeptidase', 'smcog_derived'),
        ('SMCOG1275', 'peptide deformylase', 'smcog_derived'),
        ('SMCOG1276', 'PfkB domain protein', 'smcog_derived'),
        ('SMCOG1277', 'Radical SAM domain protein', 'other'),
        ('SMCOG1278', 'PadR family transcriptional regulator', 'regulator'),
        ('SMCOG1279', 'pseudouridine synthase', 'smcog_derived'),
        ('SMCOG1280', 'thiamine-phosphate pyrophosphorylase', 'smcog_derived'),
        ('SMCOG1281', 'IS407A, transposase OrfA', 'other'),
        ('SMCOG1282', 'extracellular ligand-binding receptor', 'transporter'),
        ('SMCOG1283', '2`,3`-cyclic-nucleotide 2`-phosphodiesterase', 'smcog_derived'),
        ('SMCOG1284', 'transcriptional regulator, MarR family', 'regulator'),
        ('SMCOG1285', 'ferredoxin fdxC', 'other'),
        ('SMCOG1286', 'Pentapeptide repeat protein', 'other'),
        ('SMCOG1287', 'AraC family transcriptional regulator', 'regulator'),
        ('SMCOG1288', 'ABC transporter related protein', 'transporter'),
        ('SMCOG1289', 'hypothetical protein', 'other'),
        ('SMCOG1290', 'conserved hypothetical transmembrane protein', 'transporter'),
        ('SMCOG1291', 'argininosuccinate synthase', 'smcog_derived'),
        ('SMCOG1292', 'hypothetical protein', 'other'),
        ('SMCOG1293', 'aldehyde oxidase and xanthine dehydrogenase', 'smcog_derived'),
        ('SMCOG1294', 'Nitrilase/cyanide hydratase and apolipoprotein', 'smcog_derived'),
        ('SMCOG1295', 'Sel1 domain protein repeat-containing protein', 'other'),
        ('SMCOG1296', 'tellurium resistance protein, TerD', 'other'),
        ('SMCOG1297', 'Pullulanase, type I', 'smcog_derived'),
        ('SMCOG1298', 'putative carboxymuconolactone decarboxylase', 'smcog_derived'),
        ('SMCOG1299', 'chaperonin GroEL', 'other'),
        ('SMCOG1300', 'hypothetical protein', 'other')
    ) val ( name, description, functional_class_name )
LEFT JOIN antismash.functional_classes f ON val.functional_class_name = f.name;
