CREATE TABLE antismash.substrates (
    substrate_id	serial NOT NULL,
    name	text,
    description	text,
    CONSTRAINT substrate_pkey PRIMARY KEY (substrate_id),
    CONSTRAINT substrate_name_unique UNIQUE (name)
);

INSERT INTO antismash.substrates (name, description)
VALUES
    ('2-oxo-isovaleric-acid', '2-oxo-isovaleric-acid'),
    ('3-me-glu', '3-methyl-glutamate'),
    ('4ppro', '4-propyl-proline'),
    ('aad', '2-amino-adipic acid'),
    ('abu', '2-amino-butyric acid'),
    ('aeo', '2-amino-8-oxo-9,10-decanoate'),
    ('ala', 'alanine'),
    ('ala-b', 'beta-alanine (identical to b-ala)'),
    ('ala-d', 'D-alanine'),
    ('alaninol', 'alaninol'),
    ('alle', 'allo-isoleucine'),
    ('allo-thr', 'allo-threonine'),
    ('alpha-hydroxy-isocaproic-acid', 'alpha-hydroxy-isocaproic-acid'),
    ('aoda', 'S-2-amino-8-oxodecanoic acid'),
    ('arg', 'arginine'),
    ('asn', 'asparagine'),
    ('asp', 'aspartic acid'),
    ('b-ala', 'beta-alanine'),
    ('beta-ala', 'beta-alanine (identical to b-ala)'),
    ('bht', 'beta-hydroxy-tyrosine'),
    ('bmt', '4-butenyl-4-methyl threonine'),
    ('cap', 'capreomycidine'),
    ('ccemal', 'double-bonded ethylmalonyl'),
    ('ccmal', 'double-bonded malonyl-CoA'),
    ('ccmmal', 'reduced methylmalonyl'),
    ('ccmxmal', 'double-bonded methoxymalonyl'),
    ('cys', 'cysteine'),
    ('dab', '2,4-diaminobutyric acid'),
    ('dhb', '2,3-dihydroxy-benzoic acid'),
    ('dhpg', '3,5-dihydroxy-phenyl-glycine'),
    ('dht', 'dehydro-threonine/2,3-dehydroaminobutyric acid'),
    ('d-lyserg', 'D-lysergic acid'),
    ('dpg', '3,5-dihydroxy-phenyl-glycine (identical to dhpg)'),
    ('emal', 'ethylmalonyl-CoA'),
    ('gln', 'glutamine'),
    ('glu', 'glutamic acid'),
    ('gly', 'glycine'),
    ('haorn', 'L-δ-N-acetyl-δ-N-hydroxyornithine/L-Nδ-hydroxy-Nδ-acylornithine'),
    ('hasn', 'hydroxyasparagine'),
    ('hforn', 'L-Nδ-hydroxy-Nδ-formylornithine'),
    ('his', 'histidine'),
    ('hiv', '2-hydroxyisovalerate'),
    ('hiv-d', 'D-2-hydroxyisovalerate'),
    ('hmp-d', '2-hydroxy-3-methyl-pentanoic acid (D-hmp)'),
    ('horn', 'hydroxy ornithine'),
    ('hpg', '4-hydroxy-phenyl-glycine'),
    ('hyv', '4-hydroxy-L-valine'),
    ('hyv-d', '2-hydroxy-valeric acid'),
    ('ile', 'isoleucine'),
    ('iva', 'isovaline'),
    ('LDAP', 'diaminopimelic acid'),
    ('leu', 'leucine'),
    ('lys-b', 'beta-lysine'),
    ('lys', 'lysine'),
    ('mal', 'malonyl-CoA'),
    ('mmal', 'methylmalonyl-CoA'),
    ('MeHOval', '3-methyl-2-oxovaleric acid'),
    ('mephe', 'c-methyl-phenylalanine'),
    ('met', 'methionine'),
    ('meval', 'methylvaline'),
    ('mxmal', 'methoxymalonyl-CoA'),
    ('N-(1,1-dimethyl-1-allyl)Trp', 'N-(1,1-dimethyl-1-allyl)-tryptophan'),
    ('ohemal', 'hydroxy-ethylmalonyl'),
    ('ohmal', 'hydroxy-malonyl'),
    ('ohmmal', 'hydroxy-methylmalonyl'),
    ('ohmxmal', 'hydroxy-methoxymalonyl'),
    ('orn', 'ornithine'),
    ('phe', 'phenylalanine'),
    ('phg', 'phenyl-glycine'),
    ('pip', 'pipecolic acid'),
    ('pk', 'unknown polyketide'),
    ('pro', 'proline'),
    ('redemal', 'fully saturated ethylmalonyl'),
    ('redmal', 'fully saturated malonyl'),
    ('redmmal', 'fully saturated methylmalonyl'),
    ('redmxmal', 'fully saturated methoxymalonyl'),
    ('sal', 'salicylic acid'),
    ('ser', 'serine'),
    ('ser-thr', 'serine or threonine'),
    ('s-nmethoxy-trp', 's-nmethoxy-tryptophan'),
    ('tcl', '(4S)-5,5,5-trichloro-leucine'),
    ('thr', 'threonine'),
    ('trp', 'tryptophan'),
    ('tyr', 'tyrosine'),
    ('val', 'valine'),
    ('vol', 'valinol'),
    ('x', 'unknown nonribosomal peptide monomer');
